# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='users',
            new_name='user',
        ),
    ]
